# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e237ae12590927cf1d5580211887c428b87015dbce1d83d1de1814c5f264534d6da93ff3188cda8d10a2b1131fb18e6c27d6ea61241bdce85015f969e6c5f0ed

test:
  secret_key_base: 188b664d4a95dac474d37ed43a96197388fa6a36e725d36ffa5cbea37b4fc2ba7bfd7edbaf0abdb09252d01ef964191bfb495dd2b6c943afec5b9b4f26061d3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
